spring.application.name=diaghealthy
spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://users-db:5432/${USERS_DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

api.security.token.secret=uma-chave-secreta-bem-grande-para-testes

server.port=8080

rate-limiter.limit-for-period=50
rate-limiter.limit-refresh-period-ms=1000
rate-limiter.timeout-duration-ms=0