spring.application.name=diaghealthy_history

spring.sql.init.mode=always

spring.datasource.url=jdbc:postgresql://history-db:5432/${HISTORY_DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

api.security.token.secret=uma-chave-secreta-bem-grande-para-testes

server.port=8083

user-service.url=http://localhost:8080
